# Generated by Django 5.1.3 on 2024-12-10 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('lessons', '0003_alter_lesson_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ثبت شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='from_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendancea_as_from_teacher', to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='in_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='در کلاس'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='is_present',
            field=models.BooleanField(default=False, verbose_name='وضعیت حضور'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='to_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendancea_as_to_student', to=settings.AUTH_USER_MODEL, verbose_name='به دانش اموز'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در تاریخ'),
        ),
    ]
