# Generated by Django 5.1.3 on 2024-12-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmetadata',
            old_name='lession',
            new_name='lessons',
        ),
    ]
