# Generated by Django 5.1.3 on 2024-12-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusersmetadata',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='studentsmetadata',
            name='address',
            field=models.CharField(default='gut', max_length=300),
        ),
        migrations.AddField(
            model_name='studentsmetadata',
            name='father_phone_number',
            field=models.PositiveBigIntegerField(default=924),
        ),
        migrations.AddField(
            model_name='studentsmetadata',
            name='home_phone_number',
            field=models.PositiveBigIntegerField(default=924),
        ),
        migrations.AddField(
            model_name='studentsmetadata',
            name='mother_phone_number',
            field=models.PositiveBigIntegerField(default=924),
        ),
        migrations.AddField(
            model_name='teachersmetadata',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=914),
        ),
    ]
