# Generated by Django 5.1.3 on 2024-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0002_rename_lession_usersmetadata_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmetadata',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson'),
        ),
    ]
