# Generated by Django 5.1.3 on 2024-12-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_allusersmetadata_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmetadata',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='father_phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='home_phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='mother_phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='teachersmetadata',
            name='phone_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
