# Generated by Django 5.1.3 on 2024-12-04 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersmetadata_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmetadata',
            name='subject',
            field=models.CharField(choices=[('1', 'تجربی'), ('2', 'ریاضی'), ('3', 'انسانی')], default=datetime.datetime(2024, 12, 4, 23, 2, 15, 799251, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
    ]
