# Generated by Django 5.1.3 on 2024-12-08 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lessons', '0002_alter_lesson_name'),
        ('users', '0004_whateveryteacherteachforeachclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusersmetadata',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='allusersmetadata',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='allusersmetadata',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='ایا معلم است'),
        ),
        migrations.AlterField(
            model_name='allusersmetadata',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='allusersmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='address',
            field=models.CharField(max_length=300, verbose_name='ادرس خانه'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='father_phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره تلفن پدر'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='grade',
            field=models.CharField(choices=[('1', 'دهم'), ('2', 'یازدهم '), ('3', 'دوازدهم')], max_length=1, verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='home_phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره تلفن خانه'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='mother_phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره تلفن مادر'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='subject',
            field=models.CharField(choices=[('1', 'تجربی'), ('2', 'ریاضی'), ('3', 'انسانی')], max_length=1, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='studentsmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانش اموز'),
        ),
        migrations.AlterField(
            model_name='teachersmetadata',
            name='classes',
            field=models.ManyToManyField(to='auth.group', verbose_name='کلاس ها'),
        ),
        migrations.AlterField(
            model_name='teachersmetadata',
            name='lessons',
            field=models.ManyToManyField(to='lessons.lesson', verbose_name='درس ها'),
        ),
        migrations.AlterField(
            model_name='teachersmetadata',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='teachersmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='whateveryteacherteachforeachclass',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='whateveryteacherteachforeachclass',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='کلاس'),
        ),
        migrations.AlterField(
            model_name='whateveryteacherteachforeachclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='معلم'),
        ),
    ]
