# Generated by Django 5.1.3 on 2024-12-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_allusersmetadata_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsmetadata',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='teachersmetadata',
            name='classes',
        ),
    ]
