# Generated by Django 5.1.3 on 2024-12-21 08:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lessons', '0003_alter_lesson_name'),
        ('users', '0006_remove_studentsmetadata_school_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatEveryTeacherTeachForEachClass',
            new_name='TeacherLessonAssignment',
        ),
    ]
