# Generated by Django 5.1.3 on 2024-12-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_allusersmetadata_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allusersmetadata',
            unique_together=set(),
        ),
    ]
