# Generated by Django 5.1.3 on 2024-12-07 21:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('scores', '0002_alter_studentscore_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentScore',
            new_name='CreateStudentScore',
        ),
    ]
