# Generated by Django 5.1.3 on 2024-12-08 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_name'),
        ('scores', '0003_rename_studentscore_createstudentscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstudentscore',
            name='from_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_score_as_from_teacher', to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم'),
        ),
        migrations.AlterField(
            model_name='createstudentscore',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='createstudentscore',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='createstudentscore',
            name='to_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_score_as_to_student', to=settings.AUTH_USER_MODEL, verbose_name='به دانش اموز'),
        ),
    ]
