# Generated by Django 5.1.3 on 2024-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
