# Generated by Django 5.1.3 on 2024-12-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('homeworks', '0002_alter_homework_expiration_date'),
        ('lessons', '0003_alter_lesson_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.CharField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='expiration_date',
            field=models.DateField(verbose_name='مهلت اتمام'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='for_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='برای درس'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='for_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='برای کلاس'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='from_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='اپدیت شده در تاریخ'),
        ),
    ]
