# Generated by Django 5.1.3 on 2024-12-27 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش شده در تاریخ')),
                ('from_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='از طرف معلم')),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_as_student', to=settings.AUTH_USER_MODEL, verbose_name='به دانش اموز')),
            ],
        ),
    ]
